ARN: "arn:aws:kms:us-west-2:959942559142:key/50741902-049e-4dd5-8e51-0ef880eea1ac"
AWS_ACCESS_KEY_ID: "AKIA57AIJAWTJ5Z2LSGY"
AWS_SECRET_ACCESS_KEY: "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"
REGION: "us-west-2"