TOKEN_LIFE_SPAN_30S: 30
TOKEN_LIFE_SPAN_1M: 60
TOKEN_LIFE_SPAN_5M: 300
TOKEN_LIFE_SPAN_10M: 600
TOKEN_LIFE_SPAN_30M: 1800
TOKEN_LIFE_SPAN_1H: 3600
TOKEN_LIFE_SPAN_2H: 7200
TOKEN_LIFE_SPAN_4H: 14400
TOKEN_LIFE_SPAN_6H: 21600
TOKEN_LIFE_SPAN_8H: 28800
TOKEN_LIFE_SPAN_12H: 43200
TOKEN_LIFE_SPAN_24H: 86400
TOKEN_LIFE_SPAN_48H: 172800
TOKEN_LIFE_SPAN_7D: 604800
TOKEN_LIFE_SPAN_14D: 1209600
TOKEN_LIFE_SPAN_30D: 2592000

TOKEN_STATE_ISSUED: "ISSUED"
TOKEN_STATE_ACTIVE: "ACTIVE"
TOKEN_STATE_SUSPENDED: "SUSPENDED"
TOKEN_STATE_EXPIRED: "EXPIRED"
TOKEN_STATE_REVOKED: "REVOKED"
TOKEN_STATE_REFRESHED: "REFRESHED"
TOKEN_STATE_LOCKED: "LOCKED"